services:
  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - models_data:/models
      - ./jupyter/notebooks:/app/notebooks

  api:
    build: ./api
    ports:
      - "8989:8989"
    volumes:
      - models_data:/models

volumes:
  models_data:
